# Generated by Django 2.2.6 on 2019-11-23 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ic', models.CharField(blank=True, max_length=12)),
                ('personal_contact', models.CharField(blank=True, max_length=15)),
                ('office_contact', models.CharField(blank=True, max_length=15)),
                ('picture', models.ImageField(blank=True, default='account/profilePicture/None/no-img.jpg', upload_to='account/profilePicture/')),
                ('home_address_line1', models.CharField(blank=True, max_length=100)),
                ('home_address_line2', models.CharField(blank=True, max_length=100)),
                ('home_zip_code', models.CharField(blank=True, max_length=10)),
                ('home_state', models.CharField(blank=True, max_length=100)),
                ('home_country', models.CharField(blank=True, max_length=100)),
                ('work_address_line1', models.CharField(blank=True, max_length=100)),
                ('work_address_line2', models.CharField(blank=True, max_length=100)),
                ('work_zip_code', models.CharField(blank=True, max_length=10)),
                ('work_state', models.CharField(blank=True, max_length=100)),
                ('work_country', models.CharField(blank=True, max_length=100)),
                ('job', models.CharField(blank=True, max_length=100)),
                ('qualification', models.TextField(blank=True, max_length=1000)),
                ('fee_type', models.CharField(blank=True, max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
