# Generated by Django 2.2.6 on 2020-01-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200104_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='user.jpg', upload_to='account/profilePicture/'),
        ),
    ]
