# Generated by Django 2.2.6 on 2020-01-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200104_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='account/profilePicture/none/no-img.jpg', upload_to='account/profilePicture/'),
        ),
    ]
