# Generated by Django 2.2.6 on 2020-01-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200104_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='office_address',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='address',
            name='office_country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='office_state',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='office_zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
