# Generated by Django 2.2.6 on 2020-01-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200112_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='office_address',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='address',
            name='office_country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='office_state',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='office_zip_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cause',
            name='cause',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.CharField(max_length=100),
        ),
    ]
