# Generated by Django 2.2.6 on 2020-01-12 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
                ('location', models.TextField(blank=True, max_length=128)),
                ('user_id', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Logistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, max_length=128)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistic', to='event.Event')),
                ('user_id', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128)),
                ('category', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True, max_length=128)),
                ('collaboration', models.CharField(blank=True, max_length=128)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='event.Event')),
            ],
        ),
    ]
