# Generated by Django 2.2.6 on 2020-01-14 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20200114_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistic',
            name='user_id',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
