# Generated by Django 2.2.6 on 2020-01-14 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20200114_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistic',
            name='user_id',
            field=models.ManyToManyField(blank=True, related_name='logistice_team', to=settings.AUTH_USER_MODEL),
        ),
    ]
